services:
  front_service:
    build:
      context: ./front_service
    ports:
      - "5001:5001"
    depends_on:
      - back_service
    devices:
      - /dev/video0:/dev/video0

  back_service:
    build:
      context: ./back_service
    ports:
      - "5002:5002"
